### ISSUE TITLE
Please release the fix to the "flushTBQueue" bug!

### ISSUE THREAD

**Issue by nikita-volkov** [haskell/stm#16] opened 2018-09-04 11:10 UTC
[The fix has been committed](https://github.com/metrix-ai/stm/commit/4f63bbc36f399ab4740d7a92f536067f42f7463b#diff-56d2dbdb1ab0700e8ee1d2fe548386ab) 5 months ago, why is it not released yet? I've just detected this bug myself and can confirm that the above commit does fix the issue.

**Comment by hvr** [comment] 2018-09-05 14:20
The next planned release is stm-2.5.0.0 which was intended to be released as soon as GHC 8.6.1 final is released (as it's bundled also w/ GHC 8.6.1) which is expected to happen RSN

**Comment by nikita-volkov** [comment] 2018-09-05 17:12
Why not release a hotfix sooner? I mean it's a bug and people don't expect bugs in such core libraries. Because of that, for instance, I blamed every component in my system and spent like 4 hours debugging before I found out that it was "stm" to blame. There must be others who could share the same story.

**Comment by hvr** [comment] 2018-09-08 09:02
@nikita-volkov I didn't realise it was such a criticial bug. I'm now planning to issue a `stm-2.4.5.1` patch-level release to fix this bug; however, do you happen to have a small repro case for exposing the bug? I'd like to take this occasion to start a new testsuite for `stm`

**Comment by hvr** [comment] 2018-09-08 09:39
Resolved by https://hackage.haskell.org/package/stm-2.4.5.1

**Closed by hvr** 2018-09-08 09:39 UTC
