### ISSUE TITLE
TBQueue of size 0 doesn't work as expected

### ISSUE THREAD

**Issue by infinity0** [haskell/stm#28] opened 2020-05-29 19:27 UTC
If you have a TBQueue of size 2, you can put 3 times on it, then the 3rd call will block until you read from the queue (from another thread).

If you have a TBQueue of size 1, you can put 2 times on it, then the 2nd call will block until you read from the queue (from another thread):

~~~~
Control.Concurrent.STM.TBQueue> q <- newTBQueueIO 1 :: IO (TBQueue ())
Control.Concurrent.STM.TBQueue> a <- async $ (atomically $ writeTBQueue q ()) >> print "wrote"
"wrote"
Control.Concurrent.STM.TBQueue> a <- async $ (atomically $ writeTBQueue q ()) >> print "wrote"
Control.Concurrent.STM.TBQueue> atomically $ readTBQueue q
"wrote"
Control.Concurrent.STM.TBQueue>
~~~~

Therefore, if you have a TBQueue of size 0, you'd expect that you can put 1 time on it, then the 1st call will block until you read from the queue (from another thread). However this doesn't work:

~~~~
Control.Concurrent.STM.TBQueue> q <- newTBQueueIO 0 :: IO (TBQueue ())
Control.Concurrent.STM.TBQueue> a <- async $ (atomically $ writeTBQueue q ()) >> print "wrote"
Control.Concurrent.STM.TBQueue> atomically $ readTBQueue q
--- hangs forever
~~~~

**Comment by infinity0** [comment] 2020-07-14 23:29
Generally when you notice a pattern, you should think harder before calling it a coincidence. :)

A blocking queue of capacity 0 that works as I described is a well-known concept in this type of programming, rust [supports it in a general way](https://doc.rust-lang.org/std/sync/mpsc/fn.sync_channel.html), java [supports it in a specific way](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/SynchronousQueue.html), kotlin [supports it in a general way](https://play.kotlinlang.org/hands-on/Introduction%20to%20Coroutines%20and%20Channels/08_Channels).

**Comment by gbaz** [comment] 2020-07-14 23:39
The ticket is named poorly. This is not a bug. It is a feature request for a different semantics, which corresponds to a different set of expectations. There's arguments for various "expected" semantics, but putting on the level of which is "correct" as opposed to "both desirable and straightforward to implement" is a recipe for a bad discussion.

**Comment by infinity0** [comment] 2020-07-14 23:56
Why would you consider other people claiming the current behavior is "incorrect" as a "recipe for bad discussion"? Generally, bugs exist, and people have different opinions on things including what things are bugs.

Two languages I mentioned implement the behaviour in the same general data structure (capacity = 0 or more); java implements it in a special data structure and throws IllegalArgumentException when you try to instantiate the general data structure with capacity = 0.

I'm not even sure what use is the current Haskell behaviour for capacity = 0, you can neither read nor write from it, they both block indefinitely!

**Comment by ChristopherKing42** [comment] 2020-07-15 00:09
The semantics in Haskell is that writes block when the queue is at capacity and reads block when the queue is empty. It sounds like to do what you want you'd use a capacity 1 queue instead. No need to change how the 0 capacity queue works.

**Comment by infinity0** [comment] 2020-07-15 00:10
No, capacity 1 doesn't work - the difference is as I described in my first post. There is a cross-language common convention for the behaviour here.

**Comment by gbaz** [comment] 2020-07-15 00:10
@infinity0 getting correct and performant stm structures is a bit tricky. If you wanted to write a patch that preserved existing characteristics and behavior in every case but the 0 case, I'm sure it would be well received. But insisting that a feature request is really about "expected behavior" won't win you any friends among maintainers.

**Comment by gbaz** [comment] 2020-07-15 00:14
That said, its easy enough to handle this special case behavior (if its ever desired, and its not clear to my why it would be especially useful) by wrapping an MVar containing a Maybe value.

**Comment by ChristopherKing42** [comment] 2020-07-15 00:14
@infinity0 wait, you want the read and the write to happen at the same time? That simple isn't possible in STM due to its ACID guarantees (specifically isolation).

**Comment by gbaz** [comment] 2020-07-15 00:15
Christopher as I understand it the desired semantics is the write blocks until a read. That's doable. I just don't see _why_.

**Comment by ChristopherKing42** [comment] 2020-07-15 00:20
@gbaz is it? If the write retries, the read wouldn't see the write, correct? You'd need to split the write into two transactions, one to write, and the other to block, correct?

**Comment by gbaz** [comment] 2020-07-15 00:23
Just create an mvar with Nothing. Writes of `Just a` to it block. The read atomically checks if the mvar is nothing, and if so takes it, then recurs, and if it is `Just a` then swaps it for a `Nothing` and returns. I think that works.

**Comment by ChristopherKing42** [comment] 2020-07-15 00:35
@gbaz doesn't `retry` make the transaction rollback all the changes it made? TMVar calls `retry` when it blocks.

**Comment by gbaz** [comment] 2020-07-15 00:39
Good point. What I described gives you a TBQueue that works but not one that works atomically. Since the fundamental unit of stm is an MVar, which is a 1 element TBQueue, conceptually, this is rather tricky to overcome.

**Comment by gbaz** [comment] 2020-07-15 03:50
Wait, nevermind, what I described is reasonable. Sure retry will roll the changes back, but then, conceptually, it'll do them again, until it succeeds. The external effect is a block. That's how stm works. Witness the description of observed behavior (which has "blocking") in the original post.

Anyway, it seems feasible, if genuinely desired, as a one-off. But I don't understand the use-case.

**Comment by infinity0** [comment] 2020-07-15 11:51
The general motivation is to ensure the message passing happens atomically / synchronously and there is no "gap" in the middle which forces you to think about distributed systems topics. A channel of capacity 1 approximates this but there is still a chance that the writer (and other threads) proceeds with further work before the reader reads the message. The concept is sometimes called "rendezvous" and it seems there's been [a little bit of previous work on it from the Haskell perspective](https://www.google.com/search?q=haskell+rendezvous).

It may be easier to implement it as a special data structure outside of `TBQueue`. But then `newTBQueue 0` should throw an exception; the current behaviour does not do anything useful - all writes block, all reads block.

**Comment by konsumlamm** [comment] 2023-09-08 01:02
According to Simon Marlow, this is not possible with STM (see https://www.oreilly.com/library/view/parallel-and-concurrent/9781449335939/ch10.html#sec_stm-whynot).

**Comment by infinity0** [comment] 2023-09-18 19:18
Thanks for digging that up. In that case might I suggest that `newTBQueue 0` fail with an error messaging explaining this and pointing the programmer to something more suitable e.g. https://hackage.haskell.org/package/synchronous-channels-0.2

**Comment by konsumlamm** [comment] 2023-09-18 20:48
With https://github.com/haskell/stm/pull/70, `newTBQueue 0` will indeed fail.

**Comment by bgamari** [comment] 2023-10-05 21:04
#70 has been merged.

**Closed by bgamari** 2023-10-05 21:04 UTC

**Comment by franciscograjales11** [comment] 2024-06-26 08:47
o

**Comment by franciscograjales11** [comment] 2024-06-26 08:47
p
